INSERT INTO country_configuration (property_group, property, description) VALUES ('dealer', 'dealerInterfaceRequiresDocs', 'Dealer interface requires documents');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', true);
INSERT INTO country_configuration (property_group, property, description) VALUES ('dealer', 'loanAppRequiresIdCopyAndDataVerification', 'Add dealer loan requires id copy and data verification');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('dealer', 'returnMaxPrincipal6000ForUnofficialEmployedNoConfirm', 'Return max principal 600 for unofficial employed no confirmation');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('dealer', 'useHomeAddressInDealerLoan', 'Use home address in dealer loan');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', true);
INSERT INTO country_configuration (property_group, property, description) VALUES ('dealer', 'setAlternativeContactOtherRelative', 'Set alternative contact other relative');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('client', 'validateEmployerRegCode', 'Validate employer reg code');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('client', 'validatePhoneNumbers', 'Validate phone numbers (except gsm)');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('web-integration', 'enablePayOutToPostaOtherwiseToBank', 'Enable pay out to posta otherwise to bank');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('next-offer', 'enableLastValidLoanAppNotBasic', 'Enable last valid loan app is not Basic or Basic Entry');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('next-offer', 'checkComfortTurnoverForNextOffer', 'Check comfort turnover for next offer');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', true);
INSERT INTO country_configuration (property_group, property, description) VALUES ('files', 'checkAttachableSignedAgreementExists', 'Check if signed agreement already exists');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('files', 'enableDataVerification', 'Enable data verification check');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', true);
INSERT INTO country_configuration (property_group, property, description) VALUES ('files', 'addBankStatementEnabled', 'Enable add bank statement');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', true);
INSERT INTO country_configuration (property_group, property, description) VALUES ('files', 'enableGeneralConditions', 'Enable general conditions');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('files', 'enableAddBrandedCards', 'Enable add branded cards');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('files', 'enableIsShowBankStatement', 'Enable show bank statement');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('reports', 'enableCollectionDateFilterForInternalCollectionCompany', 'Enable collection date filter for specific internal collection companies');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('reports', 'use360DaysInProvisionReportOtherwise365', 'Use 360 days in provision report otherwise 365');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('reports', 'getSpecialPortfolioReportOverview', 'Get special portfolio overview');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('reports', 'getMoldovaSpecificCoefsForProvisionReport', 'Get moldova specific coefs for provision report');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('car', 'validateCarRegNr', 'Validate car reg nr');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('car', 'validateCarRegDocNrAs9Or10Chars', 'Validate car reg doc nr as 9 or 10 characters');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('car', 'validateCarColor', 'Validate car color');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'showInfodebitErrors', 'Show infodebit errors');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'validateLoanAppCarRegDocNr', 'Validate loan app car reg doc nr');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', true);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'validateLoanAppCarRegNr', 'Validate loan app car reg nr');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', true);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'enablePostaEmployeesCantGetFidelBiggerThan1000', 'Enable posta employees cant get fidel bigger than 1000');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'enableAgreementSignedBeforeFaRelease', 'Enable agreement signed before fa release');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'markAsCashReleaseAllowed', 'If agreement for posta submitted loan is uploaded by Iute employee, then mark loan as cash release allowed');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'enableRequiredDocumentsCheck', 'Enable required documents check');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', true);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'enableUpdateAgriculturalAssests', 'Enable upate agricultural assets');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', true);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'enablePreactivationOfSubmittedLoans', 'Enable preactivation of submitted loans');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'confirmCashReleaseAllowed', 'Allow cash release confirmation');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'setFirstPaymentDateOtherwise1stOfMonth', 'Set payment date otherwise 1st of month');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'savePrintLoanAgreementRow', 'Save print loan agreement row');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'getPaidMonths1ForNotDealerLoans', 'Get paid months 1 for not dealer loans');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'isAuthoriseCashReleaseRequired', 'Is authorise cash release required');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', true);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'getRejectionIncasoDebtOtherwiseBadPerf', 'Get rejection incaso debt otherwise bad perf');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('loan_app', 'getActiveLoanLimit2Otherwise1', 'Get active loan limit 2 otherwise 1');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('comfort', 'enableFileChecksForComfort', 'Enable file checks for comfort');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('comfort', 'allowComfortSmsSigningWithoutFa', 'Allow comfort sms signing without FA');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('user', 'isSpecialAgentEnabled', 'Enable special agent role');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('user', 'enableWorkingMenAndCallCenterOtherwiseAll', 'Enable working men and call center otherwise all');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('user', 'thirdAndFourthCallToMen', 'Assign third and fourth rem call to men');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('user', 'usePayOutAccountantInsteadOfUsual', 'Use pay put accountant instead of usual');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);
INSERT INTO country_configuration (property_group, property, description) VALUES ('installment', 'showTotalsInInstallmentTable', 'Show totals in installment table');
insert into property(country_config_id, type, boolean_value) values ((select max(id) from country_configuration), 'boolean', false);

INSERT INTO ff4j_features (feat_uid, enable, description, strategy, expression, groupname) VALUES ('bpay-repayments-task-job', 0, 'Enable bpay payments job', NULL, NULL, NULL);
INSERT INTO ff4j_features (feat_uid, enable, description, strategy, expression, groupname) VALUES ('cobranded-card-upload-task-job', 0, 'Enable cobranded card upload job', NULL, NULL, NULL);
INSERT INTO ff4j_features (feat_uid, enable, description, strategy, expression, groupname) VALUES ('currency-rate-task-job', 0, 'Enable currency rate job', NULL, NULL, NULL);
INSERT INTO ff4j_features (feat_uid, enable, description, strategy, expression, groupname) VALUES ('send-signed-agreements-job', 0, 'Enable send signed agreements job', NULL, NULL, NULL);