INSERT INTO PUBLIC.loan_products
(id,
 admission_fee_perc,
 delay_interest,
 max_interest,
 max_loan_period,
 max_principal,
 min_interest,
 min_loan_period,
 min_principal,
 NAME,
 requires_identity_files,
 type,
 min_reminder_debt,
 min_termination_debt,
 suspension_fee,
 apr_threshold,
 req_id_copy,
 req_salary_cert,
 min_apr,
 max_apr,
 pm_default,
 delay_days,
 min_delay_debt,
 salary_ratio_regular,
 salary_ratio_second_active,
 salary_ratio_unofficial,
 guarantee_fee_perc,
 guarantee_max_period,
 guarantee_product,
 apr_threshold_guarantee,
 max_delay_days,
 paid_inst_records_threshold,
 turnover_threshold,
 official_paid_inst_records_threshold,
 official_turnover_threshold,
 max_suspended_days,
 salary_cert_limit,
 official_paid_inst_records_threshold_office,
 official_turnover_threshold_office,
 paid_inst_records_threshold_office,
 turnover_threshold_office,
 enabled,
 sort_order,
 internal_collection_days,
 car_loan,
 max_car_value_perc,
 apr_threshold_evening,
 apr_threshold_evening_guarantee,
 closed_loans_archival_threshold_years,
 defaulted_loans_archival_threshold_years,
 dept_collection_days,
 first_call_days,
 first_letter_days,
 first_letter_fee,
 first_sms_days,
 first_sms_text,
 fourth_call_days,
 invitation_text,
 payment_sms_days,
 preclaim_days,
 second_call_days,
 second_letter_days,
 second_letter_fee,
 second_sms_days,
 second_sms_text,
 term_alert_letter_days,
 term_alert_letter_fee,
 term_letter_days,
 term_letter_days_max,
 term_letter_fee_perc,
 term_sms_days,
 thankyou_notice,
 third_call_days,
 third_letter_days,
 third_letter_fee,
 third_sms_days,
 guarantee_monthly_max,
 sms_sign_limit,
 requires_data_verification)
VALUES      (24,
  25,
  0.6,
  22,
  36,
  105000,
  11,
  3,
  5000,
  'Auto Credit (Pledge)',
  NULL,
  'regular',
  50,
  0,
  65,
  NULL,
  true,
  false,
  40,
  80,
  false,
  4,
  50,
  45,
  55,
  45,
  NULL,
  NULL,
  false,
  NULL,
  180,
  3,
  0,
  3,
  0,
  17,
  NULL,
  6,
  0,
  6,
  0,
  false,
  99,
  40,
  true,
  100,
  NULL,
  NULL,
  3,
  5,
  70,
  5,
  10,
  200,
  8,
  'Field not used',
  33,
  NULL,
  2,
  NULL,
  13,
  20,
  200,
  18,
  'Field not used',
  30,
  200,
  50,
  50,
  30,
  38,
             NULL,
             22,
             NULL,
             NULL,
             27,
             NULL,
             NULL,
             false);

INSERT INTO PUBLIC.loan_product_settings
(
 check_docs_duration,
 checking_duration,
 scoring_duration,
 notify_client_duration,
 pay_out_duration,
 upload_agreement_duration,
 vip,
 loan_product_id,
 send_precontract_duration,
 allow_cash_release_duration,
 dealer_id,
 type,
 check_score_duration,
 check_official_duration,
 check_official_short_duration,
 check_unofficial_altcontact_duration,
 check_unofficial_employer_duration,
 check_unofficial_person_duration,
 check_balance_duration,
 deposit_money_duration,
 issue_card_duration,
 issue_pin_duration,
 bonus_task_duration_until_paid_out)
VALUES      (
  NULL,
  NULL,
  NULL,
  15,
  120,
  15,
  false,
  24,
  NULL,
  15,
  NULL,
  'general',
  27,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
             NULL,
             NULL,
             30);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (11.85,
             11.85,
             17,
             17,
             5000,
             105000,
             3,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (12.7,
             12.7,
             17,
             17,
             5000,
             105000,
             4,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (13.55,
             13.55,
             17,
             17,
             5000,
             105000,
             5,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (15.25,
             15.25,
             17.5,
             17.5,
             5000,
             105000,
             7,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (14.4,
             14.4,
             17.5,
             17.5,
             5000,
             105000,
             6,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (16.1,
             16.1,
             17.5,
             17.5,
             5000,
             105000,
             8,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (16.95,
             16.95,
             18,
             18,
             5000,
             105000,
             9,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (17.8,
             17.8,
             18,
             18,
             5000,
             105000,
             10,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (18.65,
             18.65,
             18,
             18,
             5000,
             105000,
             11,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (19.5,
             19.5,
             18.5,
             18.5,
             5000,
             105000,
             12,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (20.35,
             20.35,
             18.5,
             18.5,
             5000,
             105000,
             13,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (21.2,
             21.2,
             18.5,
             18.5,
             5000,
             105000,
             14,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (22.05,
             22.05,
             19,
             19,
             5000,
             105000,
             15,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (22.95,
             22.95,
             19,
             19,
             5000,
             105000,
             16,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (23.75,
             23.75,
             19,
             19,
             5000,
             105000,
             17,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (24.6,
             24.6,
             19.5,
             19.5,
             5000,
             105000,
             18,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (25.55,
             25.55,
             19.5,
             19.5,
             5000,
             105000,
             19,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (26.75,
             26.75,
             19.5,
             19.5,
             5000,
             105000,
             20,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (27.3,
             27.3,
             20,
             20,
             5000,
             105000,
             21,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (28.35,
             28.35,
             20,
             20,
             5000,
             105000,
             22,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (29.45,
             29.45,
             20,
             20,
             5000,
             105000,
             23,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (30.15,
             30.5,
             20.5,
             20.5,
             5000,
             105000,
             24,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (30.9,
             30.9,
             20.5,
             20.5,
             5000,
             105000,
             25,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (31.95,
             31.95,
             20.5,
             20.5,
             5000,
             105000,
             26,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (32.35,
             32.35,
             21,
             21,
             5000,
             105000,
             27,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (33.35,
             33.35,
             21,
             21,
             5000,
             105000,
             28,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (34.35,
             34.35,
             21,
             21,
             5000,
             105000,
             29,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (34.8,
             34.8,
             21.5,
             21.5,
             5000,
             105000,
             30,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (35.65,
             35.65,
             21.5,
             21.5,
             5000,
             105000,
             31,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (36.85,
             36.85,
             21.5,
             21.5,
             5000,
             105000,
             32,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (37.35,
             37.35,
             22,
             22,
             5000,
             105000,
             33,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (38.2,
             38.2,
             22,
             22,
             5000,
             105000,
             34,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (39.05,
             39.05,
             22,
             22,
             5000,
             105000,
             35,
             24);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (39.9,
             39.9,
             22,
             22,
             5000,
             105000,
             36,
             24);

INSERT INTO PUBLIC.loan_product_car_value_perc
(
 car_value_from,
 car_value_to,
 max_loan_perc,
 loan_product_id)
VALUES      (
             5000,
             65001,
             90,
             24);

INSERT INTO PUBLIC.loan_product_car_value_perc
(
 car_value_from,
 car_value_to,
 max_loan_perc,
 loan_product_id)
VALUES      (
             65001,
             85001,
             80,
             24);

INSERT INTO PUBLIC.loan_product_car_value_perc
(
 car_value_from,
 car_value_to,
 max_loan_perc,
 loan_product_id)
VALUES      (
             85001,
             400000,
             70,
             24);