INSERT INTO loan_products
(id,
 admission_fee_perc,
 apr_threshold,
 delay_days,
 delay_interest,
 max_apr,
 max_interest,
 max_loan_period,
 max_principal,
 min_apr,
 min_delay_debt,
 min_interest,
 min_loan_period,
 min_principal,
 min_reminder_debt,
 min_termination_debt,
 NAME,
 pm_default,
 req_id_copy,
 req_salary_cert,
 suspension_fee,
 type,
 salary_ratio_regular,
 salary_ratio_second_active,
 salary_ratio_unofficial,
 apr_threshold_guarantee,
 guarantee_fee_perc,
 guarantee_max_period,
 guarantee_product,
 max_delay_days,
 paid_inst_records_threshold,
 turnover_threshold,
 max_suspended_days,
 official_paid_inst_records_threshold,
 official_turnover_threshold,
 salary_cert_limit,
 official_paid_inst_records_threshold_office,
 official_turnover_threshold_office,
 paid_inst_records_threshold_office,
 turnover_threshold_office,
 enabled,
 sort_order,
 internal_collection_days,
 car_loan,
 max_car_value_perc,
 apr_threshold_evening,
 apr_threshold_evening_guarantee,
 guarantee_monthly_max,
 sms_sign_limit,
 requires_data_verification)
VALUES      ( 101,
  34,
  NULL,
  4,
  0.5,
  350,
  17,
  8,
  100000,
  90,
  375,
  12,
  1,
  10000,
  375,
  0,
  'FFF',
  false,
  true,
  false,
  500,
  'regular',
  33.4,
  40,
  33.4,
  NULL,
  0.25,
  999,
  true,
  180,
  4,
  0,
  17,
  4,
  0,
  50000.1,
  4,
  0,
  4,
  0,
  true,
              1,
              40,
              false,
              0,
              NULL,
              NULL,
              200,
              NULL,
              false);

INSERT INTO loan_product_settings
(allow_cash_release_duration,
 check_docs_duration,
 dealer_id,
 checking_duration,
 check_score_duration,
 scoring_duration,
 notify_client_duration,
 pay_out_duration,
 send_precontract_duration,
 type,
 upload_agreement_duration,
 vip,
 loan_product_id,
 check_official_duration,
 check_official_short_duration,
 check_unofficial_altcontact_duration,
 check_unofficial_employer_duration,
 check_unofficial_person_duration,
 check_balance_duration,
 deposit_money_duration,
 issue_card_duration,
 issue_pin_duration,
 bonus_task_duration_until_paid_out)
VALUES      ( 30,
  NULL,
  NULL,
  45,
  30,
  15,
  15,
  60,
  NULL,
  'general',
  15,
  false,
  101,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
              NULL,
              30);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (10.5,
             10.5,
             17,
             17,
             NULL,
             NULL,
             1,
             101);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (14.5,
             14.5,
             17,
             17,
             NULL,
             NULL,
             2,
             101);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (19,
             19,
             17,
             17,
             NULL,
             NULL,
             3,
             101);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (22,
             22,
             17,
             17,
             NULL,
             NULL,
             4,
             101);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (24,
             24,
             17,
             17,
             NULL,
             NULL,
             5,
             101);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (27,
             27,
             12,
             12,
             NULL,
             NULL,
             6,
             101);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (28.5,
             28.5,
             17,
             17,
             NULL,
             NULL,
             7,
             101);

INSERT INTO PUBLIC.loan_product_condition
(commission_perc,
 commission_perc_cash,
 interest_perc,
 interest_perc_cash,
 loan_amount_from,
 loan_amount_to,
 period,
 loan_product_id)
VALUES      (30,
             30,
             17,
             17,
             NULL,
             NULL,
             8,
             101);